version: '3.7'
services:
  themableappbuilder:
    image: node:10
    command: npm run dev
    volumes:
     - .:/app
    working_dir: /app
    ports:
     - "3000:3010"
     - "3001:3011"
     - "3002:3012"
